- name: second job
  hosts: demo_sut
  tasks:
    - name: Import slave config files
      template:
        src: files/ifcfg-slave-base.j2
        dest: /etc/sysconfig/network-scripts/ifcfg-{{ ansible_interfaces[item] }}
      with_items:
        - 1
        - 2

    - name: Create Bond0 file
      template:
        src: files/ifcfg-bond0-base.j2
        dest: /etc/sysconfig/network-scripts/ifcfg-bond0
      become: True

    - name: Create VLAN Bond0 file
      template:
        src: files/ifcfg-bond0-vlan.j2
        dest: /etc/sysconfig/network-scripts/ifcfg-bond0.{{ vlan_result.stdout }}
      become: True

#    - name: Restart Network Service
#      service:
#        name: network
#        state: restarted
