- name: first job
  hosts: localhost
  tasks:
    - name: "Artifact integration test results to the web"
      debug:
        msg: "200"
      register: result

    - name: "Artifact URL of test results to Tower Workflows"
      set_stats:
        data:
          vlan_result:  "{{ result.msg }}"
